export const DashboardActionTypes = {
    ENTER_EDIT_MODE: 'ENTER_EDIT_MODE',
    CANCEL_EDIT_MODE: 'CANCEL_EDIT_MODE',
    SAVE_AND_EXIT_EDIT_MODE: 'SAVE_AND_EXIT_EDIT_MODE',
    DELETE_WIDGET: 'DELETE_WIDGET',
    MOVE_ROW_DOWN: 'MOVE_ROW_DOWN',
    MOVE_ROW_UP: 'MOVE_ROW_UP',
    ADD_WIDGET: 'ADD_WIDGET',
    OPEN_ADD_WIDGET_MODAL: 'OPEN_ADD_WIDGET_MODAL',
    CLOSE_ADD_WIDGET_MODAL: 'CLOSE_ADD_WIDGET_MODAL',
};
